# Generated by Django 5.2.6 on 2026-05-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_options_alter_message_options_and_more'),
        ('chat', '0002_messageattachment'),
    ]

    operations = [
    ]
